name: Publish Quarto Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          Rscript -e "install.packages(c('httr', 'jsonlite'))"
      - run: quarto render
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
